name: Python FastAPI CI/CD

on:
  push:
    branches:
      - main  # Workflow будет запускаться при пуше в ветку main
  pull_request:
    branches:
      - main  # Также будет запускаться при создании PR в эту ветку

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Клонируем репозиторий

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Устанавливаем Python версии 3.9
name: CI/CD for FastAPI app

on:
  push:
    branches:
      - main  # Будет срабатывать при пуше в ветку main
  pull_request:
    branches:
      - main  # Будет срабатывать при PR в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Настроим Python, установим зависимости
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # 3. Устанавливаем зависимости из requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Собираем Docker-образ
    - name: Build Docker image
      run: docker build -t myfastapiapp .

    # 5. Подключаемся к серверу и деплоим приложение через SSH
    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem root@$SERVER_IP "docker pull myfastapiapp || true"
        ssh -i private_key.pem root@$SERVER_IP "docker stop myfastapiapp || true && docker rm myfastapiapp || true"
        ssh -i private_key.pem root@$SERVER_IP "docker run -d --name myfastapiapp -p 80:8000 myfastapiapp"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

    - name: Run tests
      run: |
        pytest  # Запуск тестов с использованием pytest
